version: "2" 
plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
## other configuration excluded from example...
exclude_patterns:
- "vendor"
- "assets"
- "public"
- ".env"